// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PricingEngine.Db;

#nullable disable

namespace PricingEngine.Migrations
{
    [DbContext(typeof(PricingEngineDbContext))]
    [Migration("20230212125207_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("PricingEngine.Db.Entities.DbInputEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<double>("CapitalRiskRateWeight")
                        .HasColumnType("float");

                    b.Property<int>("CreditRiskAllocation")
                        .HasColumnType("int");

                    b.Property<double>("MaintenanceRate")
                        .HasColumnType("float");

                    b.Property<double>("PrepaymentRate")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.ToTable("DbInputs");

                    b.HasData(
                        new
                        {
                            Id = new Guid("95a971e0-90f2-43d7-8444-6cd2b60d400f"),
                            CapitalRiskRateWeight = 1.5,
                            CreditRiskAllocation = 0,
                            MaintenanceRate = 2.0,
                            PrepaymentRate = 7.0
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
